version: '3.3'

services:
  database:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=activage
      - POSTGRES_PASSWORD=activage
      - POSTGRES_DB=activage-maintenance-panel
    ports:
      - 5432:5432